version: '3.6'

services:
  db:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    image: 'postgres:11-alpine'
    restart: always
    volumes:
      - ./tmp/dumps:/dumps
      - 'pgdata:/var/lib/postgresql/data'
  web:
    build: .
    depends_on:
      - db
    environment:
      MIX_ENV: dev
      # keep iex history; thanks https://stackoverflow.com/a/70419094/1870317
      ERL_AFLAGS: -kernel shell_history enabled -kernel shell_history_path '"~/shell/history"'
    env_file:
      - .env
    ports:
      - '4000:4000'
    volumes:
      - .:/app
      - type: volume
        source: shell_history
        target: /shell/history

volumes:
  shell_history:
  pgdata:
