FROM gitpod/workspace-postgresql

RUN wget https://packages.erlang-solutions.com/erlang/debian/pool/elixir_1.13.4-1~debian~bullseye_all.deb
RUN dpkg -i elixir_1.13.4-1~debian~bullseye_all.deb
RUN apt-get update
RUN apt-get install esl-erlang -y
RUN apt-get apt-cache showpkg elixir
RUN apt-get install elixir -y
RUN apt-get install inotify-tools -y
RUN mix local.hex --force
RUN mix local.rebar --force
RUN apt-get clean && rm -rf /var/cache/apt/* && rm -rf /var/lib/apt/lists/* && rm -rf /tmp/*
