#!/bin/sh

# script/test: Run tests within docker-compose. Optionally pass in a path to an
#              individual test file to run a single test.

set -e

echo "==> run tests..."

if [ -n "$1" ]; then
  # pass arguments to test call. This is useful for calling a single test.
  docker-compose run -e MIX_ENV=test web mix test "$1"
else
  docker-compose run -e MIX_ENV=test web mix test
fi
