name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 24.1
          elixir-version: 1.13.4

      - run: mix deps.get
      - run: mix deps.compile

  format-check:
    runs-on: ubuntu-latest
    needs: deps
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 24.1
          elixir-version: 1.13.4

      - run: mix format --check-formatted

  test:
    runs-on: ubuntu-latest
    needs: deps

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 24.1
          elixir-version: 1.13.4

      - run: mix deps.get
      - run: mix test
        env:
          POSTGRES_HOST: localhost
