name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cache-deps:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: [1.13.4]
        otp: [24.1]
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - uses: actions/cache@v3
        id: mix-cache
        with:
          path: |
            deps
            _build
            priv/plts
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}

      - name: Install Dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          mix deps.get
          mix deps.compile

  format-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: [1.13.4]
        otp: [24.1]
    needs: cache-deps
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - uses: actions/cache@v3
        with:
          path: |
            deps
            _build
            priv/plts
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}

      - run: mix format --check-formatted

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: [1.13.4]
        otp: [24.1]
    needs: cache-deps

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - uses: actions/cache@v3
        with:
          path: |
            deps
            _build
            priv/plts
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}

      - run: mix test
        env:
          POSTGRES_HOST: localhost
          GUARDIAN_SECRET_KEY: XsXcf+2Ar+i1Zj4zCcwQ5jKeSn6ORnzne2iVBz3WKegiPTYjmtEY6frUat2UsAUS
          LIVEVIEW_SECRET_SALT: bo6FvjYPaPjJpof/OKsB6hI2EAWOE5W7

      # upload screenshots after failed tests, they can be downloaded at the
      # bottom of the action run's summary page
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: screenshots
          path: /home/runner/work/dujudu/dujudu/screenshots/

