name: Fly Deploy
on:
  push:
    branches:
    - main
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: touch .env.prod
        - run: echo ${{ secrets.SECRET_KEY_BASE }} >> .env.prod
        - run: echo ${{ secrets.DATABASE_URL }} >> .env.prod
        - run: echo ${{ secrets.GUARDIAN_SECRET_KEY }} >> .env.prod
        - run: echo ${{ secrets.LIVEVIEW_SECRET_SALT }} >> .env.prod
        - run: flyctl deploy --remote-only
